name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  ftp-deploy:
    name: 📦 FTP Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v3

      - name: 📤 Deploy via git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp

          git config git-ftp.url "ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}/${{ secrets.PROJECT_PATH }}/"
          git config git-ftp.insecure true # Use this if you have a self-signed certificate

          git push