name: 🚀 Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: 📦 SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v3

      - name: 📤 Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_SERVER_PORT }}
          source: "./"
          target: ${{ secrets.PROJECT_PATH }}

      - name: 🚨 Trigger Laravel post-deploy hook
        run: 'curl -X POST ${{ secrets.PROJECT_URL }} -H "Authorization: ${{ secrets.DEPLOY_TOKEN }}"'

